version: "2"
services:
    frontend:
        build: ./frontend
        image: webapp-frontend
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - api
        networks:
            - webappnetwork
    api:
        build: ./api
        image: webapp-api
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - "27017:27017"
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
